INSERT INTO CUSTOMER(ID, NAME, SURNAME) VALUES (1, 'MYNAME', 'MYSURNAME');
INSERT INTO CUSTOMER(ID, NAME, SURNAME) VALUES (2, 'MYNAME2', 'MYSURNAME2');
INSERT INTO CUSTOMER(ID, NAME, SURNAME) VALUES (3, 'MYNAME3', 'MYSURNAME3');

INSERT INTO ACCOUNT(BALANCE, CUSTOMER_ID) VALUES (10, 1);
INSERT INTO ACCOUNT(BALANCE, CUSTOMER_ID) VALUES (30, 1);
INSERT INTO ACCOUNT(BALANCE, CUSTOMER_ID) VALUES (20, 2);
INSERT INTO ACCOUNT(BALANCE, CUSTOMER_ID) VALUES (40, 2);
INSERT INTO ACCOUNT(BALANCE, CUSTOMER_ID) VALUES (30, 3);

INSERT INTO TRANSACTION (AMOUNT, ACCOUNT_ID) VALUES (10, 1);
INSERT INTO TRANSACTION (AMOUNT, ACCOUNT_ID) VALUES (30, 2);
INSERT INTO TRANSACTION (AMOUNT, ACCOUNT_ID) VALUES (20, 3);
INSERT INTO TRANSACTION (AMOUNT, ACCOUNT_ID) VALUES (40, 4);
INSERT INTO TRANSACTION (AMOUNT, ACCOUNT_ID) VALUES (30, 5);